#!/bin/bash

HYBRID_CMD="systemctl hybrid-sleep"
LOCK_CMD="loginctl lock-sessions"
MIN=$1

BAT_STATUS=`cat /sys/class/power_supply/BAT0/status`
BAT_LEVEL=$(cat /sys/class/power_supply/BAT0/capacity)

usage()
{
  cat << EOF
Usage: $0 [1-100]

  Takes a percentage which is compared against the current battery percentage.
  If the current battery percentage <= provided percentage, then hybrid-sleep the system.
EOF
}

if [ -z $1 ] || [ $1 -lt 1 -o $1 -gt 100 ]
then
  usage
  exit
fi

if [ "$BAT_STATUS" = "Disharging" ] && [ $BAT_LEVEL -le $MIN ]
then
  $LOCK_CMD
  sleep 0.200
  $HYBRID_CMD
fi
